### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Arsur3215Loki** [Glitched-Out/zero-sievert-mods#1]
The mod is set to Version 28.03, Requires a newer update.

**Comment by igonro** [comment]
Hey @Arsur3215Loki, I just released the mod for the new version :sunglasses:

You can download it in [the releases page](https://github.com/Glitched-Out/zero-sievert-mods/releases/tag/v0.29.4)

Thanks for using the mod, it makes me happy! :relaxed:
